apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 1
  selector:
    matchLabels:
    app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - image: gcr.io/gcp-devops-training-389818/gcpdevops:latest
        name: gcp-devops-gke
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
